name: battery_info_plugin
description: A Flutter plugin to get battery information using Android BatteryManager API.
version: 0.0.1
homepage: https://your-plugin-homepage.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.battery_info_plugin
        pluginClass: BatteryInfoPlugin